### PR TITLE
add test cases for fedora|centos|rhel

### PR DESCRIPTION
**Pull request by haiyanmeng**
Currently the test suite of runc is based on a ubuntu docker image, `runc/script/test_Dockerfile`. 

This PR adds test suite Dockerfiles for fedora-based, centos-based, rhel-based docker image.

### CODE REVIEW

**Comment by haiyanmeng** [comment]
@rhatdan , @mrunalp , PTAL.
`test_Dockerfile_fedora` and `test_Dockerfile_centos` have been tested on the runc master + https://github.com/opencontainers/runc/pull/901.

I will give `test_Dockerfile_rhel` a new try on RHEL 7 VM.

**Comment by cyphar** [comment]
Surely it matters more what the host kernel is? Docker containers don't have systemd or anything else that might make the tests different on different distributions. Or am I missing something? Since the tests will run on the same machine, how much of a difference does the system libraries make?

**Comment by rhatdan** [comment]
We have found several issues in the past with running docker tests on our distribution rather then just running the default.  Going through this process has already found a couple of issues with runc on older kernels/userspaces.

**Comment by cyphar** [comment]
That's interesting, I wouldn't have expected that (at SUSE we run all of the integration tests inside a virtual host (not in a container)).

**Comment by haiyanmeng** [comment]
@rhatdan , @mrunalp , I just rebased this branch on top of the upstream master. According to `git log`, I do not think I really did anything incorrectly. However, this PR starts showing all the commits since the PR was first created.

Is there some way to fix this?

**Comment by cyphar** [comment]
You need to rebase your master branch as well. The diff of this PR is based on what branch you want to merge into.

**Comment by haiyanmeng** [comment]
@cyphar , thanks.
I recently shifted the directory for developing my feature branches from `$GOPATH/src/github.com/hmeng-19/runc` to `$GOPATH/src/github.com/opencontainers/runc`. 
I just rebased my branch on the upstream master, and forgot rebasing on my master.

**Pull request closed without merging**
